### ISSUE TITLE
scrolling to top from element bug

### ISSUE THREAD

**Issue by eybarta** [alvarotrigo/skrollTop.js#3]
Hi, thanks for this great little plugin..

there's one small issue I found when I tried to scrollTo 0 using an element..
In your code you have a variable -- start, which always uses the window or document properties,
but when using an element scroll properties that number will always be 0.

changing the line (44) in your code fixed it for me:
var start = **element!==window ? element.scrollTop** : (window.pageYOffset || document.documentElement.scrollTop)  - (document.documentElement.clientTop || 0);

I wasn't sure if somehow I got this wrong and I'm misusing your code, or maybe this
will be useful for someone else..

thx again

**Comment by alvarotrigo** [comment]
Thanks for the feedback @eybarta !! 
Do you feel like modifying the file yourself and creating a pull request? This way you'll appear as a collaborator. 

If not, I'll change it following your suggestion ;)

**Comment by eybarta** [comment]
Sure, PR created :)
