### ISSUE TITLE
www.npmjs.com

### ISSUE THREAD

**Issue by gabskoro** [alvarotrigo/skrollTop.js#6]
I need something light like this, could you please push it to [npm](https://www.npmjs.com)? :)

**Comment by alvarotrigo** [comment]
I'll do! Thanks for reminding it to me!

**Comment by marvinhuebner** [comment]
It would be awesome to have this on npm! :-)

**Comment by alvarotrigo** [comment]
Done!
I've added it to npm and bower. 

More about it on the installation section.
https://github.com/alvarotrigo/skrollTop.js#installation
